---
title: "R functions"
---

## Functions in R

R functions are predefined pieces of code that we can call by writing the **function name** and telling R a number of **function arguments**. Function arguments are pieces of information a function needs to know in order to perform its task (very rarely, a function may not need any argument to perform its task). The general syntax for calling a function looks like this:

```{r}
#| eval: false
function_name(argument1, argument2, ...)
```

That is, we first write the function's name, and then define all required arguments in parentheses. If we do that correctly, the function will perform its task. Depending on the function, we will see an output in the console.

:::{.alert .alert-info}
You already know two functions from the chapter on R objects. 

The first is the function *c*, we used to create vectors. The arguments the function *c* requires are the elements we want to combine into a vector.

The second function we already used is the function *matrix*. This functions requires a vector, the number of rows and the number of columns as arguments.
:::

